name: Building EShop Projects
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ["8.0.x"]
    steps:
      - name: Checkout the Projects
        uses: actions/checkout@v4
        
      - name: Show directory structure (optional)
        run: tree  # If you want to see a tree-like structure, ensure 'tree' is installed
        
      - name: List files in the repository
        run: |
          ls -R  # List files recursively to confirm the path
          
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v5.0.0
        with:
          dotnet-version: ${{matrix.dotnet-version}}

      - name: Restore Packages
        run: dotnet restore ./EShopWeb/EShopWeb.sln

      - name: Build Project
        run: dotnet build ./EShopWeb/EShopWeb.sln --configuration Release --no-restore

      - name: Publish FunctionApp
        run: dotnet publish ./EShopFunctionApp/EShopFunctionApp.csproj -o ./published_EShopFunctionApp
        
      - name: Publish WebApp
        run: dotnet publish ./EShopWeb/EShopWeb.csproj -o ./published_EShopWeb  
              
      - name: Check full path and zip published EShopFunctionApp files
        run: |
          echo "Current directory: $(pwd)"  # Print the current working directory
          echo "Listing contents in the absolute path: $(pwd)/published_EShopFunctionApp"
          ls -R $(pwd)/published_EShopFunctionApp  # List files with absolute path
          # Now zip the files using absolute paths
          zip -r $(pwd)/published_EShopFunctionApp.zip $(pwd)/published_EShopFunctionApp 
          
      - name: Check full path and zip published EShopWeb files
        run: |
          echo "Current directory: $(pwd)"  # Print the current working directory
          echo "Listing contents in the absolute path: $(pwd)/published_EShopWeb"
          ls -R $(pwd)/published_EShopWeb  # List files with absolute path
          # Now zip the files using absolute paths
          zip -r $(pwd)/published_EShopWeb.zip $(pwd)/published_EShopWeb
          
      - name: Show directory structure (optional)
        run: tree  # If you want to see a tree-like structure, ensure 'tree' is installed
